---  
- name: First VKR
  hosts: all
  become: true
  vars:
   packages:
       - mc
       - htop
       - atop
       - ncdu   
  tasks:
  
#------NewUser=myuser on Debian------------------------
    - name: NewUser Debian
      user:
        name: myuser
        password: "{ {  pwd | password_hash('sha512') } }"
        state: present
        shell: /bin/bash
        groups: sudo
      when: ansible_os_family=="Debian"

#------NewUser=myuser on OracleLinux-----------------
    - name: NewUser RedHat
      user:
        name: myuser
        password: "{ {  'qwerty21' | password_hash('sha512') } }"
        state: present
        shell: /bin/bash
        groups: wheel
      when: ansible_os_family=="RedHat"
#------Key myuser on Redhat-------------------------   
    - name: Создать SSH ключ для anscfg в ~anscfg/.ssh/id_rsa
      user:
        name: myuser
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: /home/kroot/.ssh/id_rsa
    - name: Добавить authorized key из файла id_rsa.pub
      authorized_key:
        user: myuser
        state: present
        key: "{{ lookup('file', '/home/kroot/.ssh/id_rsa') }}""
#-----PasswordAuthentication no--------------------
    - name: Disallow SSH password authentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication"
        line="PasswordAuthentication no" state=present
      notify:
        - Restart sshd
#------Install on Debian-----------------------        
    - name: Update and install required system packages Debian
      apt:
        pkg: "{{pakages}}"
        update_cache: yes
        state: latest
      when: ansible_os_family=="Debian"
#------Install on OracleLinux-----------------------
    - name: Update and install required system packages Redhat
      yum:
        pkg: "{{pakages}}"
        force_apt_get: yes
        update_cache: yes
        state: latest
      when: ansible_os_family=="RedHat"
  handlers:
     - name: Restart sshd
       service: name=sshd  state=restarted

    
 
         
   

